### PR TITLE
Update to Android N

### PR DESCRIPTION
**Pull request by danielpassos**

### CODE REVIEW

**Comment by danielpassos** [comment]
@secondsun Sanity review?

**Comment by danielpassos** [comment]
@secondsun Sanity review?

**Comment by corinnekrych** [comment]
@danielpassos mmmm Travis unhappy because of android-24:
[ERROR] Failed to execute goal org.codehaus.mojo:properties-maven-plugin:1.0.0:read-project-properties (default) on project android-24: Properties could not be loaded from File: /usr/local/android-sdk/platforms/android-24/source.properties

are we missing something? wrong travis image?

**Comment by danielpassos** [comment]
@secondsun @corinnekrych I'm going to close it in favor of add API Level 25 in [maven-android-sdk-deployer/](https://github.com/simpligility/maven-android-sdk-deployer/) first

**Pull request closed without merging**
